# Funding options for AgentVerse Marketplace
# You can add your funding platforms here

# Example funding platforms (uncomment and configure as needed):
# github: [agentverse]
# patreon: agentverse
# open_collective: agentverse
# ko_fi: agentverse
# custom: ['https://agentverse.com/donate', 'https://agentverse.com/sponsor']
